# Site settings
title:       notkenobi.xyz
author:      Luke Cottage
description: ":rocket: A responsive Jekyll theme based on mashlo internet site"
baseurl:     ""
url:         "http://notkenobi.xyz"

# Social Links
#email:            nope
twitter_username: luca9dario
github_username:  x21Kenobi

# Build settings
markdown: kramdown
permalink: pretty
