# Site settings
title:       notkenobi.xyz
author:      Luke Cottage
description: "There is nothing here, yet! :eyes:"
baseurl:     ""
url:         "http://notkenobi.xyz"

# Social Links
#email:            nope
twitter_username: luca9dario
github_username:  x21Kenobi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
